apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: scheduler-framework-demo
    leaderElection:
      leaderElect: true
      lockObjectName: scheduler-framework-demo
      lockObjectNamespace: kube-system
    plugins:
      filter:
        enabled:
        - name: "demoscheduler"
      preBind:
        enabled:
        - name: "demoscheduler"
    pluginConfig:
    - name: "demoscheduler"
      args: {"master": "master", "kubeconfig": "kubeconfig"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-framework-demo
  namespace: kube-system
  labels:
    component: scheduler-framework-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler-framework-demo
  template:
    metadata:
      labels:
        component: scheduler-framework-demo
    spec:
      serviceAccount: demo-sa
      priorityClassName: system-cluster-critical
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - name: scheduler-ctrl
        image: ccr.ccs.tencentyun.com/kinderyj/exscheduler:v0.03
        imagePullPolicy: IfNotPresent
        args:
        - scheduler-framework-demo
        - --config=/scheduler/scheduler-config.yaml
        - --v=5
        resources:
          requests:
            cpu: "50m"
        volumeMounts:
        - name: scheduler-config
          mountPath: /scheduler
